Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [2]:
data = pd.read_csv('Data.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [4]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [5]:
X = data.iloc[: , :-1].values
Y = data.iloc[: , -1].values

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [7]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Handling missing data

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[: , 1:3])
X[: , 1:3] = imputer.transform(X[: , 1:3])

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical data (one hot encoding)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [13]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


Splitting dataset into training set and test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [15]:
print(X_train)

[[0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 54000.0]]


In [16]:
print(X_test)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 50.0 83000.0]]


In [17]:
print(Y_train)

[1 1 0 0 1 1 0 0]


In [18]:
print(Y_test)

[1 0]


Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
X_train[: , 3:] = sc.fit_transform(X_train[: , 3:])
X_test[: , 3:] = sc.transform(X_test[: , 3:])

In [21]:
print(X_train)

[[0.0 0.0 1.0 -1.5994558542741337 -1.3477524318226022]
 [1.0 0.0 0.0 -0.3477077944074203 -0.34008706223560986]
 [0.0 0.0 1.0 0.12169772804259728 -0.037787451359512204]
 [0.0 0.0 1.0 0.24339545608519456 -0.9446862839878052]
 [1.0 0.0 0.0 -0.03477077944074192 0.5668117703926832]
 [1.0 0.0 0.0 1.686382802875989 1.7760102138970737]
 [1.0 0.0 0.0 1.0605087729426323 1.0706444551861791]
 [0.0 1.0 0.0 -1.1300503318241162 -0.7431532100704068]]


In [22]:
print(X_test)

[[0.0 1.0 0.0 0.4346347430092756 0.24211959574798594]
 [0.0 1.0 0.0 1.9993198178426677 2.1790763617318705]]
